name: Build and Test

on:
  push:
    branches:
      - feature/*
      - chore/*
      - fix/*
  schedule:
    - cron: '0 */6 * * *'
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        swift package clean
        swift build -v
    - name: Run tests
      run: swift test -v
